// This file is generated by play-room-protocol. Do not edit by hand.
// Regenerate with: cargo run -p play-room-protocol --bin generate-web-protocol

export const PROTOCOL_VERSION = 2 as const;

export const PROTOCOL_VALUES = {
  server_message_kinds: ["response", "event"],

  client_request_types: ["connect", "list_rooms", "create_room", "join_room", "spectate_room", "leave_room", "start_next_match", "set_ready", "set_spectator", "submit_move", "ping"],

  server_result_statuses: ["ok", "error", "welcome", "room_list", "room_snapshot", "pong"],

  server_event_types: ["notice", "room_event", "room_snapshot"],

  room_event_types: ["player_joined", "player_left", "player_disconnected", "player_reconnected", "ready_changed", "role_changed", "round_started", "move_accepted", "round_resolved", "game_ended", "match_reset", "host_changed"],

  room_phase_types: ["lobby", "in_round", "finished"],

  game_kinds: ["rock_paper_scissors", "rock_paper_scissors_lizard_spock"],

  moves: ["rock", "paper", "scissors", "lizard", "spock"],

  rps_moves: ["rock", "paper", "scissors"],

  player_roles: ["participant", "spectator"],

  error_codes: ["invalid_request", "room_not_found", "room_name_exists", "player_name_exists", "room_full", "room_limit_reached", "client_limit_reached", "not_in_room", "match_not_finished", "host_only", "invalid_action"],

  round_end_reasons: ["all_moves_submitted", "timeout", "player_left"],

  round_outcomes: ["draw", "win", "timeout_win", "no_contest"]
} as const;
