// This file is generated by play-room-protocol. Do not edit by hand.
// Regenerate with: cargo run -p play-room-protocol --bin generate-web-protocol

export const CLIENT_ENVELOPE_SCHEMA = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ClientEnvelope",
  "type": "object",
  "required": [
    "request",
    "request_id"
  ],
  "properties": {
    "request": {
      "$ref": "#/definitions/ClientRequest"
    },
    "request_id": {
      "type": "integer",
      "format": "uint64",
      "minimum": 0.0
    }
  },
  "definitions": {
    "ClientRequest": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "name",
            "type"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "reconnect_token": {
              "type": [
                "string",
                "null"
              ]
            },
            "type": {
              "type": "string",
              "enum": [
                "connect"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "list_rooms"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "name",
            "type"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "rules": {
              "anyOf": [
                {
                  "$ref": "#/definitions/GameRules"
                },
                {
                  "type": "null"
                }
              ]
            },
            "type": {
              "type": "string",
              "enum": [
                "create_room"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "room_id",
            "type"
          ],
          "properties": {
            "room_id": {
              "type": "string"
            },
            "type": {
              "type": "string",
              "enum": [
                "join_room"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "room_id",
            "type"
          ],
          "properties": {
            "room_id": {
              "type": "string"
            },
            "type": {
              "type": "string",
              "enum": [
                "spectate_room"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "mode",
            "room_id",
            "type"
          ],
          "properties": {
            "mode": {
              "$ref": "#/definitions/EnterRoomMode"
            },
            "room_id": {
              "type": "string"
            },
            "type": {
              "type": "string",
              "enum": [
                "enter_room"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "name",
            "type"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "type": {
              "type": "string",
              "enum": [
                "update_display_name"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "target_score",
            "type"
          ],
          "properties": {
            "target_score": {
              "type": "integer",
              "format": "uint32",
              "minimum": 0.0
            },
            "type": {
              "type": "string",
              "enum": [
                "update_match_format"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "leave_room"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "start_next_match"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "ready",
            "type"
          ],
          "properties": {
            "ready": {
              "type": "boolean"
            },
            "type": {
              "type": "string",
              "enum": [
                "set_ready"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "spectator",
            "type"
          ],
          "properties": {
            "spectator": {
              "type": "boolean"
            },
            "type": {
              "type": "string",
              "enum": [
                "set_spectator"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "mv",
            "type"
          ],
          "properties": {
            "mv": {
              "$ref": "#/definitions/Move"
            },
            "type": {
              "type": "string",
              "enum": [
                "submit_move"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "ping"
              ]
            }
          }
        }
      ]
    },
    "EnterRoomMode": {
      "type": "string",
      "enum": [
        "auto",
        "participant",
        "spectator"
      ]
    },
    "GameKind": {
      "type": "string",
      "enum": [
        "rock_paper_scissors",
        "rock_paper_scissors_lizard_spock"
      ]
    },
    "GameRules": {
      "type": "object",
      "required": [
        "allow_spectators",
        "game",
        "max_players",
        "min_players",
        "round_seconds",
        "target_score"
      ],
      "properties": {
        "allow_spectators": {
          "type": "boolean"
        },
        "game": {
          "$ref": "#/definitions/GameKind"
        },
        "max_players": {
          "type": "integer",
          "format": "uint",
          "minimum": 0.0
        },
        "min_players": {
          "type": "integer",
          "format": "uint",
          "minimum": 0.0
        },
        "round_seconds": {
          "type": "integer",
          "format": "uint64",
          "minimum": 0.0
        },
        "target_score": {
          "type": "integer",
          "format": "uint32",
          "minimum": 0.0
        }
      }
    },
    "Move": {
      "type": "string",
      "enum": [
        "rock",
        "paper",
        "scissors",
        "lizard",
        "spock"
      ]
    }
  }
} as const;

export const SERVER_MESSAGE_SCHEMA = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ServerMessage",
  "oneOf": [
    {
      "type": "object",
      "required": [
        "kind",
        "request_id",
        "result"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "enum": [
            "response"
          ]
        },
        "request_id": {
          "type": "integer",
          "format": "uint64",
          "minimum": 0.0
        },
        "result": {
          "$ref": "#/definitions/ServerResult"
        }
      }
    },
    {
      "type": "object",
      "required": [
        "event",
        "kind"
      ],
      "properties": {
        "event": {
          "$ref": "#/definitions/ServerEvent"
        },
        "kind": {
          "type": "string",
          "enum": [
            "event"
          ]
        }
      }
    }
  ],
  "definitions": {
    "ErrorCode": {
      "type": "string",
      "enum": [
        "invalid_request",
        "room_not_found",
        "room_name_exists",
        "player_name_exists",
        "room_full",
        "room_limit_reached",
        "client_limit_reached",
        "not_in_room",
        "match_not_finished",
        "host_only",
        "invalid_action"
      ]
    },
    "GameKind": {
      "type": "string",
      "enum": [
        "rock_paper_scissors",
        "rock_paper_scissors_lizard_spock"
      ]
    },
    "GameRules": {
      "type": "object",
      "required": [
        "allow_spectators",
        "game",
        "max_players",
        "min_players",
        "round_seconds",
        "target_score"
      ],
      "properties": {
        "allow_spectators": {
          "type": "boolean"
        },
        "game": {
          "$ref": "#/definitions/GameKind"
        },
        "max_players": {
          "type": "integer",
          "format": "uint",
          "minimum": 0.0
        },
        "min_players": {
          "type": "integer",
          "format": "uint",
          "minimum": 0.0
        },
        "round_seconds": {
          "type": "integer",
          "format": "uint64",
          "minimum": 0.0
        },
        "target_score": {
          "type": "integer",
          "format": "uint32",
          "minimum": 0.0
        }
      }
    },
    "Move": {
      "type": "string",
      "enum": [
        "rock",
        "paper",
        "scissors",
        "lizard",
        "spock"
      ]
    },
    "PlayerRole": {
      "type": "string",
      "enum": [
        "participant",
        "spectator"
      ]
    },
    "PlayerScore": {
      "type": "object",
      "required": [
        "name",
        "player_id",
        "score"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "player_id": {
          "type": "string"
        },
        "score": {
          "type": "integer",
          "format": "uint32",
          "minimum": 0.0
        }
      }
    },
    "PlayerView": {
      "type": "object",
      "required": [
        "connected",
        "id",
        "name",
        "ready",
        "role",
        "score"
      ],
      "properties": {
        "connected": {
          "type": "boolean"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "participant_seat_expires_at_ms": {
          "type": [
            "integer",
            "null"
          ],
          "format": "uint64",
          "minimum": 0.0
        },
        "ready": {
          "type": "boolean"
        },
        "role": {
          "$ref": "#/definitions/PlayerRole"
        },
        "score": {
          "type": "integer",
          "format": "uint32",
          "minimum": 0.0
        },
        "spectator_expires_at_ms": {
          "type": [
            "integer",
            "null"
          ],
          "format": "uint64",
          "minimum": 0.0
        }
      }
    },
    "RoomEvent": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "event",
            "name",
            "player_id",
            "role"
          ],
          "properties": {
            "event": {
              "type": "string",
              "enum": [
                "player_joined"
              ]
            },
            "name": {
              "type": "string"
            },
            "player_id": {
              "type": "string"
            },
            "role": {
              "$ref": "#/definitions/PlayerRole"
            }
          }
        },
        {
          "type": "object",
          "required": [
            "event",
            "player_id"
          ],
          "properties": {
            "event": {
              "type": "string",
              "enum": [
                "player_left"
              ]
            },
            "player_id": {
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "required": [
            "event",
            "player_id"
          ],
          "properties": {
            "event": {
              "type": "string",
              "enum": [
                "player_disconnected"
              ]
            },
            "player_id": {
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "required": [
            "event",
            "player_id"
          ],
          "properties": {
            "event": {
              "type": "string",
              "enum": [
                "player_reconnected"
              ]
            },
            "player_id": {
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "required": [
            "event",
            "name",
            "player_id"
          ],
          "properties": {
            "event": {
              "type": "string",
              "enum": [
                "player_renamed"
              ]
            },
            "name": {
              "type": "string"
            },
            "player_id": {
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "required": [
            "event",
            "target_score"
          ],
          "properties": {
            "event": {
              "type": "string",
              "enum": [
                "match_format_changed"
              ]
            },
            "target_score": {
              "type": "integer",
              "format": "uint32",
              "minimum": 0.0
            }
          }
        },
        {
          "type": "object",
          "required": [
            "event",
            "player_id",
            "ready"
          ],
          "properties": {
            "event": {
              "type": "string",
              "enum": [
                "ready_changed"
              ]
            },
            "player_id": {
              "type": "string"
            },
            "ready": {
              "type": "boolean"
            }
          }
        },
        {
          "type": "object",
          "required": [
            "event",
            "player_id",
            "role"
          ],
          "properties": {
            "event": {
              "type": "string",
              "enum": [
                "role_changed"
              ]
            },
            "player_id": {
              "type": "string"
            },
            "role": {
              "$ref": "#/definitions/PlayerRole"
            }
          }
        },
        {
          "type": "object",
          "required": [
            "deadline_ms",
            "event",
            "round"
          ],
          "properties": {
            "deadline_ms": {
              "type": "integer",
              "format": "uint64",
              "minimum": 0.0
            },
            "event": {
              "type": "string",
              "enum": [
                "round_started"
              ]
            },
            "round": {
              "type": "integer",
              "format": "uint32",
              "minimum": 0.0
            }
          }
        },
        {
          "type": "object",
          "required": [
            "event",
            "player_id"
          ],
          "properties": {
            "event": {
              "type": "string",
              "enum": [
                "move_accepted"
              ]
            },
            "player_id": {
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "required": [
            "event",
            "result"
          ],
          "properties": {
            "event": {
              "type": "string",
              "enum": [
                "round_resolved"
              ]
            },
            "result": {
              "$ref": "#/definitions/RoundResult"
            }
          }
        },
        {
          "type": "object",
          "required": [
            "event"
          ],
          "properties": {
            "event": {
              "type": "string",
              "enum": [
                "game_ended"
              ]
            },
            "winner": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "event",
            "requested_by"
          ],
          "properties": {
            "event": {
              "type": "string",
              "enum": [
                "match_reset"
              ]
            },
            "requested_by": {
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "required": [
            "event"
          ],
          "properties": {
            "event": {
              "type": "string",
              "enum": [
                "host_changed"
              ]
            },
            "host_id": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        }
      ]
    },
    "RoomPhase": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "phase"
          ],
          "properties": {
            "phase": {
              "type": "string",
              "enum": [
                "lobby"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "deadline_ms",
            "phase",
            "round"
          ],
          "properties": {
            "deadline_ms": {
              "type": "integer",
              "format": "uint64",
              "minimum": 0.0
            },
            "phase": {
              "type": "string",
              "enum": [
                "in_round"
              ]
            },
            "round": {
              "type": "integer",
              "format": "uint32",
              "minimum": 0.0
            }
          }
        },
        {
          "type": "object",
          "required": [
            "phase"
          ],
          "properties": {
            "phase": {
              "type": "string",
              "enum": [
                "finished"
              ]
            },
            "winner": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        }
      ]
    },
    "RoomSnapshot": {
      "type": "object",
      "required": [
        "id",
        "name",
        "phase",
        "players",
        "round",
        "rules",
        "scoreboard"
      ],
      "properties": {
        "host_id": {
          "type": [
            "string",
            "null"
          ]
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "phase": {
          "$ref": "#/definitions/RoomPhase"
        },
        "players": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PlayerView"
          }
        },
        "round": {
          "type": "integer",
          "format": "uint32",
          "minimum": 0.0
        },
        "rules": {
          "$ref": "#/definitions/GameRules"
        },
        "scoreboard": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PlayerScore"
          }
        }
      }
    },
    "RoomSummary": {
      "type": "object",
      "required": [
        "game",
        "id",
        "max_players",
        "name",
        "phase",
        "players",
        "spectators",
        "target_score"
      ],
      "properties": {
        "game": {
          "$ref": "#/definitions/GameKind"
        },
        "id": {
          "type": "string"
        },
        "max_players": {
          "type": "integer",
          "format": "uint",
          "minimum": 0.0
        },
        "name": {
          "type": "string"
        },
        "phase": {
          "$ref": "#/definitions/RoomPhase"
        },
        "players": {
          "type": "integer",
          "format": "uint",
          "minimum": 0.0
        },
        "spectators": {
          "type": "integer",
          "format": "uint",
          "minimum": 0.0
        },
        "target_score": {
          "type": "integer",
          "format": "uint32",
          "minimum": 0.0
        }
      }
    },
    "RoundEndReason": {
      "type": "string",
      "enum": [
        "all_moves_submitted",
        "timeout",
        "player_left"
      ]
    },
    "RoundOutcome": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "draw",
            "no_contest"
          ]
        },
        {
          "type": "object",
          "required": [
            "win"
          ],
          "properties": {
            "win": {
              "type": "object",
              "required": [
                "winner"
              ],
              "properties": {
                "winner": {
                  "type": "string"
                }
              }
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "timeout_win"
          ],
          "properties": {
            "timeout_win": {
              "type": "object",
              "required": [
                "winner"
              ],
              "properties": {
                "winner": {
                  "type": "string"
                }
              }
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "RoundResult": {
      "type": "object",
      "required": [
        "outcome",
        "reason",
        "round",
        "scores",
        "submitted"
      ],
      "properties": {
        "outcome": {
          "$ref": "#/definitions/RoundOutcome"
        },
        "reason": {
          "$ref": "#/definitions/RoundEndReason"
        },
        "round": {
          "type": "integer",
          "format": "uint32",
          "minimum": 0.0
        },
        "scores": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PlayerScore"
          }
        },
        "submitted": {
          "type": "object",
          "additionalProperties": {
            "anyOf": [
              {
                "$ref": "#/definitions/Move"
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    },
    "ServerEvent": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "message",
            "type"
          ],
          "properties": {
            "message": {
              "type": "string"
            },
            "type": {
              "type": "string",
              "enum": [
                "notice"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "event",
            "room_id",
            "type"
          ],
          "properties": {
            "event": {
              "$ref": "#/definitions/RoomEvent"
            },
            "room_id": {
              "type": "string"
            },
            "type": {
              "type": "string",
              "enum": [
                "room_event"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "room",
            "type"
          ],
          "properties": {
            "room": {
              "$ref": "#/definitions/RoomSnapshot"
            },
            "type": {
              "type": "string",
              "enum": [
                "room_snapshot"
              ]
            }
          }
        }
      ]
    },
    "ServerResult": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "status"
          ],
          "properties": {
            "status": {
              "type": "string",
              "enum": [
                "ok"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "message",
            "status"
          ],
          "properties": {
            "code": {
              "anyOf": [
                {
                  "$ref": "#/definitions/ErrorCode"
                },
                {
                  "type": "null"
                }
              ]
            },
            "message": {
              "type": "string"
            },
            "status": {
              "type": "string",
              "enum": [
                "error"
              ]
            },
            "suggestions": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        {
          "type": "object",
          "required": [
            "display_name",
            "player_id",
            "protocol_version",
            "reconnect_token",
            "reconnected",
            "room_restored",
            "stale_token_replaced",
            "status"
          ],
          "properties": {
            "display_name": {
              "type": "string"
            },
            "player_id": {
              "type": "string"
            },
            "protocol_version": {
              "type": "integer",
              "format": "uint16",
              "minimum": 0.0
            },
            "reconnect_token": {
              "type": "string"
            },
            "reconnected": {
              "type": "boolean"
            },
            "room_restored": {
              "type": "boolean"
            },
            "stale_token_replaced": {
              "type": "boolean"
            },
            "status": {
              "type": "string",
              "enum": [
                "welcome"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "rooms",
            "status"
          ],
          "properties": {
            "rooms": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/RoomSummary"
              }
            },
            "status": {
              "type": "string",
              "enum": [
                "room_list"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "room",
            "status"
          ],
          "properties": {
            "room": {
              "$ref": "#/definitions/RoomSnapshot"
            },
            "status": {
              "type": "string",
              "enum": [
                "room_snapshot"
              ]
            }
          }
        },
        {
          "type": "object",
          "required": [
            "status"
          ],
          "properties": {
            "status": {
              "type": "string",
              "enum": [
                "pong"
              ]
            }
          }
        }
      ]
    }
  }
} as const;
