use crate::{
    ClientRequest, EnterRoomMode, ErrorCode, ServerEvent, ServerMessage, ServerResult,
    PROTOCOL_VERSION,
};
use play_room_core::{
    GameKind, GameRules, Move, PlayerId, PlayerRole, PlayerScore, RoomEvent, RoomId, RoomPhase,
    RoomSnapshot, RoomSummary, SessionToken,
};
use serde::Serialize;
use serde_json::Value;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProtocolManifest {
    pub protocol_version: u16,
    pub server_message_kinds: Vec<String>,
    pub client_request_types: Vec<String>,
    pub server_result_statuses: Vec<String>,
    pub server_event_types: Vec<String>,
    pub room_event_types: Vec<String>,
    pub room_phase_types: Vec<String>,
    pub game_kinds: Vec<String>,
    pub moves: Vec<String>,
    pub rps_moves: Vec<String>,
    pub player_roles: Vec<String>,
    pub enter_room_modes: Vec<String>,
    pub error_codes: Vec<String>,
    pub round_end_reasons: Vec<String>,
    pub round_outcomes: Vec<String>,
}

pub fn protocol_manifest() -> ProtocolManifest {
    ProtocolManifest {
        protocol_version: PROTOCOL_VERSION,
        server_message_kinds: server_message_kinds(),
        client_request_types: client_request_types(),
        server_result_statuses: server_result_statuses(),
        server_event_types: server_event_types(),
        room_event_types: room_event_types(),
        room_phase_types: room_phase_types(),
        game_kinds: game_kinds(),
        moves: moves(),
        rps_moves: rps_moves(),
        player_roles: player_roles(),
        enter_room_modes: enter_room_modes(),
        error_codes: error_codes(),
        round_end_reasons: round_end_reasons(),
        round_outcomes: round_outcomes(),
    }
}

pub fn typescript_types_module() -> String {
    r#"// This file is generated by play-room-protocol. Do not edit by hand.
// Regenerate with: cargo run -p play-room-protocol --bin generate-web-protocol

import type { PROTOCOL_VALUES } from './generated';

type ProtocolValues = typeof PROTOCOL_VALUES;

export type Id = string;
export type PlayerId = Id;
export type RoomId = Id;
export type SessionToken = Id;

export type GameKind = ProtocolValues['game_kinds'][number];
export type Move = ProtocolValues['moves'][number];
export type PlayerRole = ProtocolValues['player_roles'][number];
export type EnterRoomMode = ProtocolValues['enter_room_modes'][number];
export type ErrorCode = ProtocolValues['error_codes'][number];
export type RoundEndReason = ProtocolValues['round_end_reasons'][number];

export interface GameRules {
  game: GameKind;
  min_players: number;
  max_players: number;
  target_score: number;
  round_seconds: number;
  allow_spectators: boolean;
}

export type RoomPhase =
  | { phase: 'lobby' }
  | { phase: 'in_round'; round: number; deadline_ms: number }
  | { phase: 'finished'; winner: PlayerId | null };

export interface PlayerView {
  id: PlayerId;
  name: string;
  role: PlayerRole;
  ready: boolean;
  connected: boolean;
  score: number;
  participant_seat_expires_at_ms?: number | null;
  spectator_expires_at_ms?: number | null;
}

export interface PlayerScore {
  player_id: PlayerId;
  name: string;
  score: number;
}

export interface RoomSummary {
  id: RoomId;
  name: string;
  phase: RoomPhase;
  players: number;
  spectators: number;
  max_players: number;
  game: GameKind;
  target_score: number;
}

export interface RoomSnapshot {
  id: RoomId;
  name: string;
  host_id: PlayerId | null;
  phase: RoomPhase;
  rules: GameRules;
  round: number;
  players: PlayerView[];
  scoreboard: PlayerScore[];
}

export type RoundOutcome =
  | 'draw'
  | 'no_contest'
  | { win: { winner: PlayerId } }
  | { timeout_win: { winner: PlayerId } };

export interface RoundResult {
  round: number;
  reason: RoundEndReason;
  submitted: Record<PlayerId, Move | null>;
  outcome: RoundOutcome;
  scores: PlayerScore[];
}

export type RoomEvent =
  | { event: 'player_joined'; player_id: PlayerId; name: string; role: PlayerRole }
  | { event: 'player_left'; player_id: PlayerId }
  | { event: 'player_disconnected'; player_id: PlayerId }
  | { event: 'player_reconnected'; player_id: PlayerId }
  | { event: 'player_renamed'; player_id: PlayerId; name: string }
  | { event: 'match_format_changed'; target_score: number }
  | { event: 'ready_changed'; player_id: PlayerId; ready: boolean }
  | { event: 'role_changed'; player_id: PlayerId; role: PlayerRole }
  | { event: 'round_started'; round: number; deadline_ms: number }
  | { event: 'move_accepted'; player_id: PlayerId }
  | { event: 'round_resolved'; result: RoundResult }
  | { event: 'game_ended'; winner: PlayerId | null }
  | { event: 'match_reset'; requested_by: PlayerId }
  | { event: 'host_changed'; host_id: PlayerId | null };

export type ClientRequest =
  | { type: 'connect'; name: string; reconnect_token: SessionToken | null }
  | { type: 'list_rooms' }
  | { type: 'create_room'; name: string; rules: GameRules | null }
  | { type: 'join_room'; room_id: RoomId }
  | { type: 'spectate_room'; room_id: RoomId }
  | { type: 'enter_room'; room_id: RoomId; mode: EnterRoomMode }
  | { type: 'update_display_name'; name: string }
  | { type: 'update_match_format'; target_score: number }
  | { type: 'leave_room' }
  | { type: 'start_next_match' }
  | { type: 'set_ready'; ready: boolean }
  | { type: 'set_spectator'; spectator: boolean }
  | { type: 'submit_move'; mv: Move }
  | { type: 'ping' };

export interface ClientEnvelope {
  request_id: number;
  request: ClientRequest;
}

export interface WelcomeState {
  player_id: PlayerId;
  display_name: string;
  reconnect_token: SessionToken;
  protocol_version: number;
  reconnected: boolean;
  stale_token_replaced: boolean;
  room_restored: boolean;
}

export type ServerResult =
  | { status: 'ok' }
  | { status: 'error'; message: string; code?: ErrorCode | null; suggestions?: string[] }
  | {
      status: 'welcome';
      player_id: PlayerId;
      display_name: string;
      reconnect_token: SessionToken;
      protocol_version: number;
      reconnected: boolean;
      stale_token_replaced: boolean;
      room_restored: boolean;
    }
  | { status: 'room_list'; rooms: RoomSummary[] }
  | { status: 'room_snapshot'; room: RoomSnapshot }
  | { status: 'pong' };

export type ServerEvent =
  | { type: 'notice'; message: string }
  | { type: 'room_event'; room_id: RoomId; event: RoomEvent }
  | { type: 'room_snapshot'; room: RoomSnapshot };

export type ServerMessage =
  | { kind: 'response'; request_id: number; result: ServerResult }
  | { kind: 'event'; event: ServerEvent };
"#
    .to_owned()
}

pub fn typescript_constants_module() -> String {
    let manifest = protocol_manifest();
    format!(
        "// This file is generated by play-room-protocol. Do not edit by hand.\n\
         // Regenerate with: cargo run -p play-room-protocol --bin generate-web-protocol\n\n\
         export const PROTOCOL_VERSION = {protocol_version} as const;\n\n\
         export const PROTOCOL_VALUES = {{\n\
         {server_message_kinds}\n\
         {client_request_types}\n\
         {server_result_statuses}\n\
         {server_event_types}\n\
         {room_event_types}\n\
         {room_phase_types}\n\
         {game_kinds}\n\
         {moves}\n\
         {rps_moves}\n\
         {player_roles}\n\
         {enter_room_modes}\n\
         {error_codes}\n\
         {round_end_reasons}\n\
         {round_outcomes}\
         }} as const;\n",
        protocol_version = manifest.protocol_version,
        server_message_kinds = ts_field("server_message_kinds", &manifest.server_message_kinds),
        client_request_types = ts_field("client_request_types", &manifest.client_request_types),
        server_result_statuses =
            ts_field("server_result_statuses", &manifest.server_result_statuses),
        server_event_types = ts_field("server_event_types", &manifest.server_event_types),
        room_event_types = ts_field("room_event_types", &manifest.room_event_types),
        room_phase_types = ts_field("room_phase_types", &manifest.room_phase_types),
        game_kinds = ts_field("game_kinds", &manifest.game_kinds),
        moves = ts_field("moves", &manifest.moves),
        rps_moves = ts_field("rps_moves", &manifest.rps_moves),
        player_roles = ts_field("player_roles", &manifest.player_roles),
        enter_room_modes = ts_field("enter_room_modes", &manifest.enter_room_modes),
        error_codes = ts_field("error_codes", &manifest.error_codes),
        round_end_reasons = ts_field("round_end_reasons", &manifest.round_end_reasons),
        round_outcomes = ts_field_last("round_outcomes", &manifest.round_outcomes),
    )
}

fn ts_field(name: &str, values: &[String]) -> String {
    format!("  {name}: {},\n", ts_array(values))
}

fn ts_field_last(name: &str, values: &[String]) -> String {
    format!("  {name}: {}\n", ts_array(values))
}

fn ts_array(values: &[String]) -> String {
    let encoded = values
        .iter()
        .map(|value| serde_json::to_string(value).expect("protocol string should serialize"))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{encoded}]")
}

fn game_kinds() -> Vec<String> {
    simple_values(&[
        GameKind::RockPaperScissors,
        GameKind::RockPaperScissorsLizardSpock,
    ])
}

fn moves() -> Vec<String> {
    simple_values(&[
        Move::Rock,
        Move::Paper,
        Move::Scissors,
        Move::Lizard,
        Move::Spock,
    ])
}

fn rps_moves() -> Vec<String> {
    simple_values(&[Move::Rock, Move::Paper, Move::Scissors])
}

fn player_roles() -> Vec<String> {
    simple_values(&[PlayerRole::Participant, PlayerRole::Spectator])
}

fn enter_room_modes() -> Vec<String> {
    simple_values(&[
        EnterRoomMode::Auto,
        EnterRoomMode::Participant,
        EnterRoomMode::Spectator,
    ])
}

fn error_codes() -> Vec<String> {
    simple_values(&[
        ErrorCode::InvalidRequest,
        ErrorCode::RoomNotFound,
        ErrorCode::RoomNameExists,
        ErrorCode::PlayerNameExists,
        ErrorCode::RoomFull,
        ErrorCode::RoomLimitReached,
        ErrorCode::ClientLimitReached,
        ErrorCode::NotInRoom,
        ErrorCode::MatchNotFinished,
        ErrorCode::HostOnly,
        ErrorCode::InvalidAction,
    ])
}

fn round_end_reasons() -> Vec<String> {
    use play_room_core::RoundEndReason;

    simple_values(&[
        RoundEndReason::AllMovesSubmitted,
        RoundEndReason::Timeout,
        RoundEndReason::PlayerLeft,
    ])
}

fn round_outcomes() -> Vec<String> {
    use play_room_core::RoundOutcome;

    let player_id = PlayerId::new("player");
    vec![
        enum_or_object_tag(&RoundOutcome::Draw),
        enum_or_object_tag(&RoundOutcome::Win {
            winner: player_id.clone(),
        }),
        enum_or_object_tag(&RoundOutcome::TimeoutWin { winner: player_id }),
        enum_or_object_tag(&RoundOutcome::NoContest),
    ]
}

fn room_phase_types() -> Vec<String> {
    vec![
        tagged_value(&RoomPhase::Lobby, "phase"),
        tagged_value(
            &RoomPhase::InRound {
                round: 1,
                deadline_ms: 0,
            },
            "phase",
        ),
        tagged_value(&RoomPhase::Finished { winner: None }, "phase"),
    ]
}

fn room_event_types() -> Vec<String> {
    let player_id = PlayerId::new("player");
    vec![
        tagged_value(
            &RoomEvent::PlayerJoined {
                player_id: player_id.clone(),
                name: "Alice".to_owned(),
                role: PlayerRole::Participant,
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::PlayerLeft {
                player_id: player_id.clone(),
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::PlayerDisconnected {
                player_id: player_id.clone(),
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::PlayerReconnected {
                player_id: player_id.clone(),
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::PlayerRenamed {
                player_id: player_id.clone(),
                name: "Alicia".to_owned(),
            },
            "event",
        ),
        tagged_value(&RoomEvent::MatchFormatChanged { target_score: 3 }, "event"),
        tagged_value(
            &RoomEvent::ReadyChanged {
                player_id: player_id.clone(),
                ready: true,
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::RoleChanged {
                player_id: player_id.clone(),
                role: PlayerRole::Spectator,
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::RoundStarted {
                round: 1,
                deadline_ms: 0,
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::MoveAccepted {
                player_id: player_id.clone(),
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::RoundResolved {
                result: sample_round_result(),
            },
            "event",
        ),
        tagged_value(&RoomEvent::GameEnded { winner: None }, "event"),
        tagged_value(
            &RoomEvent::MatchReset {
                requested_by: player_id.clone(),
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::HostChanged {
                host_id: Some(player_id),
            },
            "event",
        ),
    ]
}

fn client_request_types() -> Vec<String> {
    let room_id = RoomId::new("room");
    vec![
        tagged_value(
            &ClientRequest::Connect {
                name: "Alice".to_owned(),
                reconnect_token: None,
            },
            "type",
        ),
        tagged_value(&ClientRequest::ListRooms, "type"),
        tagged_value(
            &ClientRequest::CreateRoom {
                name: "room".to_owned(),
                rules: None,
            },
            "type",
        ),
        tagged_value(
            &ClientRequest::JoinRoom {
                room_id: room_id.clone(),
            },
            "type",
        ),
        tagged_value(
            &ClientRequest::SpectateRoom {
                room_id: room_id.clone(),
            },
            "type",
        ),
        tagged_value(
            &ClientRequest::EnterRoom {
                room_id: room_id.clone(),
                mode: EnterRoomMode::Auto,
            },
            "type",
        ),
        tagged_value(
            &ClientRequest::UpdateDisplayName {
                name: "Alicia".to_owned(),
            },
            "type",
        ),
        tagged_value(
            &ClientRequest::UpdateMatchFormat { target_score: 3 },
            "type",
        ),
        tagged_value(&ClientRequest::LeaveRoom, "type"),
        tagged_value(&ClientRequest::StartNextMatch, "type"),
        tagged_value(&ClientRequest::SetReady { ready: true }, "type"),
        tagged_value(&ClientRequest::SetSpectator { spectator: true }, "type"),
        tagged_value(&ClientRequest::SubmitMove { mv: Move::Rock }, "type"),
        tagged_value(&ClientRequest::Ping, "type"),
    ]
}

fn server_result_statuses() -> Vec<String> {
    vec![
        tagged_value(&ServerResult::Ok, "status"),
        tagged_value(&ServerResult::error("error"), "status"),
        tagged_value(
            &ServerResult::Welcome {
                player_id: PlayerId::new("player"),
                display_name: "Alice".to_owned(),
                reconnect_token: SessionToken::new("session"),
                protocol_version: PROTOCOL_VERSION,
                reconnected: false,
                stale_token_replaced: false,
                room_restored: false,
            },
            "status",
        ),
        tagged_value(
            &ServerResult::RoomList {
                rooms: vec![sample_room_summary()],
            },
            "status",
        ),
        tagged_value(
            &ServerResult::RoomSnapshot {
                room: sample_room_snapshot(),
            },
            "status",
        ),
        tagged_value(&ServerResult::Pong, "status"),
    ]
}

fn server_event_types() -> Vec<String> {
    let room_id = RoomId::new("room");
    vec![
        tagged_value(
            &ServerEvent::Notice {
                message: "hello".to_owned(),
            },
            "type",
        ),
        tagged_value(
            &ServerEvent::RoomEvent {
                room_id,
                event: RoomEvent::PlayerLeft {
                    player_id: PlayerId::new("player"),
                },
            },
            "type",
        ),
        tagged_value(
            &ServerEvent::RoomSnapshot {
                room: sample_room_snapshot(),
            },
            "type",
        ),
    ]
}

fn server_message_kinds() -> Vec<String> {
    vec![
        tagged_value(
            &ServerMessage::Response {
                request_id: 1,
                result: ServerResult::Ok,
            },
            "kind",
        ),
        tagged_value(
            &ServerMessage::Event {
                event: ServerEvent::Notice {
                    message: "hello".to_owned(),
                },
            },
            "kind",
        ),
    ]
}

fn simple_values<T: Serialize>(values: &[T]) -> Vec<String> {
    values.iter().map(simple_value).collect()
}

fn simple_value<T: Serialize>(value: &T) -> String {
    match serde_json::to_value(value).expect("protocol value should serialize") {
        Value::String(value) => value,
        other => panic!("expected string protocol value, got {other}"),
    }
}

fn tagged_value<T: Serialize>(value: &T, tag: &str) -> String {
    match serde_json::to_value(value).expect("protocol value should serialize") {
        Value::Object(mut object) => match object.remove(tag) {
            Some(Value::String(value)) => value,
            Some(other) => panic!("expected string field {tag}, got {other}"),
            None => panic!("missing protocol tag field {tag}"),
        },
        other => panic!("expected object protocol value, got {other}"),
    }
}

fn enum_or_object_tag<T: Serialize>(value: &T) -> String {
    match serde_json::to_value(value).expect("protocol value should serialize") {
        Value::String(value) => value,
        Value::Object(object) if object.len() == 1 => object
            .keys()
            .next()
            .expect("one-key protocol object should have a key")
            .to_owned(),
        other => panic!("expected string or one-key object protocol value, got {other}"),
    }
}

fn sample_room_summary() -> RoomSummary {
    RoomSummary {
        id: RoomId::new("room"),
        name: "room".to_owned(),
        phase: RoomPhase::Lobby,
        players: 1,
        spectators: 0,
        max_players: 2,
        game: GameKind::RockPaperScissorsLizardSpock,
        target_score: 2,
    }
}

fn sample_room_snapshot() -> RoomSnapshot {
    RoomSnapshot {
        id: RoomId::new("room"),
        name: "room".to_owned(),
        host_id: Some(PlayerId::new("player")),
        phase: RoomPhase::Lobby,
        rules: GameRules::rpsls(),
        round: 0,
        players: Vec::new(),
        scoreboard: Vec::new(),
    }
}

fn sample_round_result() -> play_room_core::RoundResult {
    play_room_core::RoundResult {
        round: 1,
        reason: play_room_core::RoundEndReason::AllMovesSubmitted,
        submitted: Default::default(),
        outcome: play_room_core::RoundOutcome::Draw,
        scores: vec![PlayerScore {
            player_id: PlayerId::new("player"),
            name: "Alice".to_owned(),
            score: 0,
        }],
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{fs, path::Path};

    #[test]
    fn generated_web_protocol_constants_are_current() {
        let repo_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let generated_path = repo_root.join("web/src/lib/protocol/generated.ts");
        let generated = fs::read_to_string(&generated_path)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", generated_path.display()))
            .replace("\r\n", "\n");

        assert_eq!(generated, typescript_constants_module());
    }

    #[test]
    fn generated_web_protocol_types_are_current() {
        let repo_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let generated_path = repo_root.join("web/src/lib/protocol/generated-types.ts");
        let generated = fs::read_to_string(&generated_path)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", generated_path.display()))
            .replace("\r\n", "\n");

        assert_eq!(generated, typescript_types_module());
    }
    #[test]
    fn manifest_values_match_protocol_serialization() {
        let manifest = protocol_manifest();

        assert_eq!(manifest.protocol_version, PROTOCOL_VERSION);
        assert_eq!(manifest.server_message_kinds, vec!["response", "event"]);
        assert!(manifest
            .client_request_types
            .contains(&"enter_room".to_owned()));
        assert!(manifest
            .client_request_types
            .contains(&"update_display_name".to_owned()));
        assert!(manifest
            .client_request_types
            .contains(&"update_match_format".to_owned()));
        assert_eq!(
            manifest.enter_room_modes,
            vec!["auto", "participant", "spectator"]
        );
        assert!(manifest
            .error_codes
            .contains(&"client_limit_reached".to_owned()));
        assert!(manifest
            .room_event_types
            .contains(&"move_accepted".to_owned()));
        assert!(manifest
            .room_event_types
            .contains(&"player_renamed".to_owned()));
        assert!(manifest
            .room_event_types
            .contains(&"match_format_changed".to_owned()));
    }
}
