use crate::{ClientRequest, ErrorCode, ServerEvent, ServerMessage, ServerResult, PROTOCOL_VERSION};
use play_room_core::{
    GameKind, GameRules, Move, PlayerId, PlayerRole, PlayerScore, RoomEvent, RoomId, RoomPhase,
    RoomSnapshot, RoomSummary, SessionToken,
};
use serde::Serialize;
use serde_json::Value;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProtocolManifest {
    pub protocol_version: u16,
    pub server_message_kinds: Vec<String>,
    pub client_request_types: Vec<String>,
    pub server_result_statuses: Vec<String>,
    pub server_event_types: Vec<String>,
    pub room_event_types: Vec<String>,
    pub room_phase_types: Vec<String>,
    pub game_kinds: Vec<String>,
    pub moves: Vec<String>,
    pub rps_moves: Vec<String>,
    pub player_roles: Vec<String>,
    pub error_codes: Vec<String>,
    pub round_end_reasons: Vec<String>,
    pub round_outcomes: Vec<String>,
}

pub fn protocol_manifest() -> ProtocolManifest {
    ProtocolManifest {
        protocol_version: PROTOCOL_VERSION,
        server_message_kinds: server_message_kinds(),
        client_request_types: client_request_types(),
        server_result_statuses: server_result_statuses(),
        server_event_types: server_event_types(),
        room_event_types: room_event_types(),
        room_phase_types: room_phase_types(),
        game_kinds: game_kinds(),
        moves: moves(),
        rps_moves: rps_moves(),
        player_roles: player_roles(),
        error_codes: error_codes(),
        round_end_reasons: round_end_reasons(),
        round_outcomes: round_outcomes(),
    }
}

pub fn typescript_constants_module() -> String {
    let manifest = protocol_manifest();
    format!(
        "// This file is generated by play-room-protocol. Do not edit by hand.\n\
         // Regenerate with: cargo run -p play-room-protocol --bin generate-web-protocol\n\n\
         export const PROTOCOL_VERSION = {protocol_version} as const;\n\n\
         export const PROTOCOL_VALUES = {{\n\
         {server_message_kinds}\n\
         {client_request_types}\n\
         {server_result_statuses}\n\
         {server_event_types}\n\
         {room_event_types}\n\
         {room_phase_types}\n\
         {game_kinds}\n\
         {moves}\n\
         {rps_moves}\n\
         {player_roles}\n\
         {error_codes}\n\
         {round_end_reasons}\n\
         {round_outcomes}\
         }} as const;\n",
        protocol_version = manifest.protocol_version,
        server_message_kinds = ts_field("server_message_kinds", &manifest.server_message_kinds),
        client_request_types = ts_field("client_request_types", &manifest.client_request_types),
        server_result_statuses =
            ts_field("server_result_statuses", &manifest.server_result_statuses),
        server_event_types = ts_field("server_event_types", &manifest.server_event_types),
        room_event_types = ts_field("room_event_types", &manifest.room_event_types),
        room_phase_types = ts_field("room_phase_types", &manifest.room_phase_types),
        game_kinds = ts_field("game_kinds", &manifest.game_kinds),
        moves = ts_field("moves", &manifest.moves),
        rps_moves = ts_field("rps_moves", &manifest.rps_moves),
        player_roles = ts_field("player_roles", &manifest.player_roles),
        error_codes = ts_field("error_codes", &manifest.error_codes),
        round_end_reasons = ts_field("round_end_reasons", &manifest.round_end_reasons),
        round_outcomes = ts_field_last("round_outcomes", &manifest.round_outcomes),
    )
}

fn ts_field(name: &str, values: &[String]) -> String {
    format!("  {name}: {},\n", ts_array(values))
}

fn ts_field_last(name: &str, values: &[String]) -> String {
    format!("  {name}: {}\n", ts_array(values))
}

fn ts_array(values: &[String]) -> String {
    let encoded = values
        .iter()
        .map(|value| serde_json::to_string(value).expect("protocol string should serialize"))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{encoded}]")
}

fn game_kinds() -> Vec<String> {
    simple_values(&[
        GameKind::RockPaperScissors,
        GameKind::RockPaperScissorsLizardSpock,
    ])
}

fn moves() -> Vec<String> {
    simple_values(&[
        Move::Rock,
        Move::Paper,
        Move::Scissors,
        Move::Lizard,
        Move::Spock,
    ])
}

fn rps_moves() -> Vec<String> {
    simple_values(&[Move::Rock, Move::Paper, Move::Scissors])
}

fn player_roles() -> Vec<String> {
    simple_values(&[PlayerRole::Participant, PlayerRole::Spectator])
}

fn error_codes() -> Vec<String> {
    simple_values(&[
        ErrorCode::InvalidRequest,
        ErrorCode::RoomNotFound,
        ErrorCode::RoomNameExists,
        ErrorCode::PlayerNameExists,
        ErrorCode::RoomFull,
        ErrorCode::RoomLimitReached,
        ErrorCode::ClientLimitReached,
        ErrorCode::NotInRoom,
        ErrorCode::MatchNotFinished,
        ErrorCode::HostOnly,
        ErrorCode::InvalidAction,
    ])
}

fn round_end_reasons() -> Vec<String> {
    use play_room_core::RoundEndReason;

    simple_values(&[
        RoundEndReason::AllMovesSubmitted,
        RoundEndReason::Timeout,
        RoundEndReason::PlayerLeft,
    ])
}

fn round_outcomes() -> Vec<String> {
    use play_room_core::RoundOutcome;

    let player_id = PlayerId::new("player");
    vec![
        enum_or_object_tag(&RoundOutcome::Draw),
        enum_or_object_tag(&RoundOutcome::Win {
            winner: player_id.clone(),
        }),
        enum_or_object_tag(&RoundOutcome::TimeoutWin { winner: player_id }),
        enum_or_object_tag(&RoundOutcome::NoContest),
    ]
}

fn room_phase_types() -> Vec<String> {
    vec![
        tagged_value(&RoomPhase::Lobby, "phase"),
        tagged_value(
            &RoomPhase::InRound {
                round: 1,
                deadline_ms: 0,
            },
            "phase",
        ),
        tagged_value(&RoomPhase::Finished { winner: None }, "phase"),
    ]
}

fn room_event_types() -> Vec<String> {
    let player_id = PlayerId::new("player");
    vec![
        tagged_value(
            &RoomEvent::PlayerJoined {
                player_id: player_id.clone(),
                name: "Alice".to_owned(),
                role: PlayerRole::Participant,
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::PlayerLeft {
                player_id: player_id.clone(),
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::PlayerDisconnected {
                player_id: player_id.clone(),
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::PlayerReconnected {
                player_id: player_id.clone(),
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::ReadyChanged {
                player_id: player_id.clone(),
                ready: true,
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::RoleChanged {
                player_id: player_id.clone(),
                role: PlayerRole::Spectator,
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::RoundStarted {
                round: 1,
                deadline_ms: 0,
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::MoveAccepted {
                player_id: player_id.clone(),
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::RoundResolved {
                result: sample_round_result(),
            },
            "event",
        ),
        tagged_value(&RoomEvent::GameEnded { winner: None }, "event"),
        tagged_value(
            &RoomEvent::MatchReset {
                requested_by: player_id.clone(),
            },
            "event",
        ),
        tagged_value(
            &RoomEvent::HostChanged {
                host_id: Some(player_id),
            },
            "event",
        ),
    ]
}

fn client_request_types() -> Vec<String> {
    let room_id = RoomId::new("room");
    vec![
        tagged_value(
            &ClientRequest::Connect {
                name: "Alice".to_owned(),
                reconnect_token: None,
            },
            "type",
        ),
        tagged_value(&ClientRequest::ListRooms, "type"),
        tagged_value(
            &ClientRequest::CreateRoom {
                name: "room".to_owned(),
                rules: None,
            },
            "type",
        ),
        tagged_value(
            &ClientRequest::JoinRoom {
                room_id: room_id.clone(),
            },
            "type",
        ),
        tagged_value(
            &ClientRequest::SpectateRoom {
                room_id: room_id.clone(),
            },
            "type",
        ),
        tagged_value(&ClientRequest::LeaveRoom, "type"),
        tagged_value(&ClientRequest::StartNextMatch, "type"),
        tagged_value(&ClientRequest::SetReady { ready: true }, "type"),
        tagged_value(&ClientRequest::SetSpectator { spectator: true }, "type"),
        tagged_value(&ClientRequest::SubmitMove { mv: Move::Rock }, "type"),
        tagged_value(&ClientRequest::Ping, "type"),
    ]
}

fn server_result_statuses() -> Vec<String> {
    vec![
        tagged_value(&ServerResult::Ok, "status"),
        tagged_value(&ServerResult::error("error"), "status"),
        tagged_value(
            &ServerResult::Welcome {
                player_id: PlayerId::new("player"),
                reconnect_token: SessionToken::new("session"),
                protocol_version: PROTOCOL_VERSION,
                reconnected: false,
                stale_token_replaced: false,
                room_restored: false,
            },
            "status",
        ),
        tagged_value(
            &ServerResult::RoomList {
                rooms: vec![sample_room_summary()],
            },
            "status",
        ),
        tagged_value(
            &ServerResult::RoomSnapshot {
                room: sample_room_snapshot(),
            },
            "status",
        ),
        tagged_value(&ServerResult::Pong, "status"),
    ]
}

fn server_event_types() -> Vec<String> {
    let room_id = RoomId::new("room");
    vec![
        tagged_value(
            &ServerEvent::Notice {
                message: "hello".to_owned(),
            },
            "type",
        ),
        tagged_value(
            &ServerEvent::RoomEvent {
                room_id,
                event: RoomEvent::PlayerLeft {
                    player_id: PlayerId::new("player"),
                },
            },
            "type",
        ),
        tagged_value(
            &ServerEvent::RoomSnapshot {
                room: sample_room_snapshot(),
            },
            "type",
        ),
    ]
}

fn server_message_kinds() -> Vec<String> {
    vec![
        tagged_value(
            &ServerMessage::Response {
                request_id: 1,
                result: ServerResult::Ok,
            },
            "kind",
        ),
        tagged_value(
            &ServerMessage::Event {
                event: ServerEvent::Notice {
                    message: "hello".to_owned(),
                },
            },
            "kind",
        ),
    ]
}

fn simple_values<T: Serialize>(values: &[T]) -> Vec<String> {
    values.iter().map(simple_value).collect()
}

fn simple_value<T: Serialize>(value: &T) -> String {
    match serde_json::to_value(value).expect("protocol value should serialize") {
        Value::String(value) => value,
        other => panic!("expected string protocol value, got {other}"),
    }
}

fn tagged_value<T: Serialize>(value: &T, tag: &str) -> String {
    match serde_json::to_value(value).expect("protocol value should serialize") {
        Value::Object(mut object) => match object.remove(tag) {
            Some(Value::String(value)) => value,
            Some(other) => panic!("expected string field {tag}, got {other}"),
            None => panic!("missing protocol tag field {tag}"),
        },
        other => panic!("expected object protocol value, got {other}"),
    }
}

fn enum_or_object_tag<T: Serialize>(value: &T) -> String {
    match serde_json::to_value(value).expect("protocol value should serialize") {
        Value::String(value) => value,
        Value::Object(object) if object.len() == 1 => object
            .keys()
            .next()
            .expect("one-key protocol object should have a key")
            .to_owned(),
        other => panic!("expected string or one-key object protocol value, got {other}"),
    }
}

fn sample_room_summary() -> RoomSummary {
    RoomSummary {
        id: RoomId::new("room"),
        name: "room".to_owned(),
        phase: RoomPhase::Lobby,
        players: 1,
        spectators: 0,
        max_players: 2,
        game: GameKind::RockPaperScissorsLizardSpock,
        target_score: 2,
    }
}

fn sample_room_snapshot() -> RoomSnapshot {
    RoomSnapshot {
        id: RoomId::new("room"),
        name: "room".to_owned(),
        host_id: Some(PlayerId::new("player")),
        phase: RoomPhase::Lobby,
        rules: GameRules::rpsls(),
        round: 0,
        players: Vec::new(),
        scoreboard: Vec::new(),
    }
}

fn sample_round_result() -> play_room_core::RoundResult {
    play_room_core::RoundResult {
        round: 1,
        reason: play_room_core::RoundEndReason::AllMovesSubmitted,
        submitted: Default::default(),
        outcome: play_room_core::RoundOutcome::Draw,
        scores: vec![PlayerScore {
            player_id: PlayerId::new("player"),
            name: "Alice".to_owned(),
            score: 0,
        }],
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{fs, path::Path};

    #[test]
    fn generated_web_protocol_constants_are_current() {
        let repo_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let generated_path = repo_root.join("web/src/lib/protocol/generated.ts");
        let generated = fs::read_to_string(&generated_path)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", generated_path.display()))
            .replace("\r\n", "\n");

        assert_eq!(generated, typescript_constants_module());
    }

    #[test]
    fn manifest_values_match_protocol_serialization() {
        let manifest = protocol_manifest();

        assert_eq!(manifest.protocol_version, PROTOCOL_VERSION);
        assert_eq!(manifest.server_message_kinds, vec!["response", "event"]);
        assert!(manifest
            .client_request_types
            .contains(&"connect".to_owned()));
        assert!(manifest
            .error_codes
            .contains(&"client_limit_reached".to_owned()));
        assert!(manifest
            .room_event_types
            .contains(&"move_accepted".to_owned()));
    }
}
