use crate::{ClientEnvelope, ServerMessage};
use schemars::{schema::RootSchema, schema_for};

pub fn client_envelope_schema() -> RootSchema {
    schema_for!(ClientEnvelope)
}

pub fn server_message_schema() -> RootSchema {
    schema_for!(ServerMessage)
}

pub fn typescript_schema_module() -> String {
    format!(
        "// This file is generated by play-room-protocol. Do not edit by hand.\n\
         // Regenerate with: cargo run -p play-room-protocol --bin generate-web-protocol\n\n\
         export const CLIENT_ENVELOPE_SCHEMA = {client_schema} as const;\n\n\
         export const SERVER_MESSAGE_SCHEMA = {server_schema} as const;\n",
        client_schema = schema_json(&client_envelope_schema()),
        server_schema = schema_json(&server_message_schema()),
    )
}

fn schema_json(schema: &RootSchema) -> String {
    serde_json::to_string_pretty(schema).expect("protocol schema should serialize")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{fs, path::Path};

    #[test]
    fn generated_web_protocol_schema_is_current() {
        let repo_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let generated_path = repo_root.join("web/src/lib/protocol/schema.ts");
        let generated = fs::read_to_string(&generated_path)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", generated_path.display()))
            .replace("\r\n", "\n");

        assert_eq!(generated, typescript_schema_module());
    }

    #[test]
    fn server_message_schema_has_expected_title() {
        let schema = server_message_schema();

        assert_eq!(
            schema.schema.metadata.unwrap().title.as_deref(),
            Some("ServerMessage")
        );
    }
}
